apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: previews
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: previews
  source:
    repoURL: https://github.com/ber2go/argocd-example-apps.git
    targetRevision: HEAD
    path: pr-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: previews
  syncPolicy:
    automated:
      selfHeal: true
      prune: true