resources:
- ../../base

namespace: development

images:
- name: mcr.microsoft.com/azuredocs/aks-helloworld
  newName: docker.io/eubertgomicrosoft/docker-gs-ping
  newTag: v2

patchesJson6902:
- target:
    version: v1
    kind: Ingress
    name: hello-world-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: "pr-1.localdev.me"

patches: 
- target:
    version: v1
    kind: Deployment
    name: aks-helloworld
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "Development Environment"
  